---
    - name: Disable mouse acceleration
      osx_defaults:
        key: com.apple.mouse.scaling
        type: string
        value: -1
        state: present

    - name: "Key Repeat: Fast (all the way to the right)"
      osx_defaults:
        key: InitialKeyRepeat
        type: int
        value: 15
        state: present

    - name: "Delay Until Repeat: Short (all the way to the right)"
      osx_defaults:
        key: KeyRepeat
        type: int
        value: 2
        state: present

    - name: "Untick 'Correct spelling automatically'"
      osx_defaults:
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present

    - name: "Untick 'Add full stop with double-space'"
      osx_defaults:
        key: NSAutomaticPeriodSubstitutionEnabled
        type: bool
        value: false
        state: present

    - name: "Finder: Show path bar"
      osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true
        state: present
        
    - name: "Finder: Keep folders on top when sorting by name"
      osx_defaults:
        domain: com.apple.finder
        key: _FXSortFoldersFirst
        type: bool
        value: true
        state: present
        
    - name: "Finder: Use list view in all Finder windows by default"
      osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: Nlsv
        state: present

    - name: "Set Keybord Shortcut 'Move focus to next window' to Command+$"
      shell: |
        /usr/libexec/PlistBuddy -c 'Delete :AppleSymbolicHotKeys:27' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:enabled bool 1' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:type string standard' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters array' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:0 integer 36' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:1 integer 10' ~/Library/Preferences/com.apple.symbolichotkeys.plist
        /usr/libexec/PlistBuddy -c 'Add :AppleSymbolicHotKeys:27:value:parameters:2 integer 1048576' ~/Library/Preferences/com.apple.symbolichotkeys.plist
       
    - name: Download Powerline fonts
      git:
        repo: https://github.com/powerline/fonts.git
        dest: $HOME/fonts
        depth: 1

    - name: Install powerline fonts
      shell: cp -r $HOME/fonts/*/*.ttf /Library/Fonts/.
      
