---
    - name: Install Rider
      homebrew_cask: 
        name: "rider"
        state: present

    - name: Install Spotify
      homebrew_cask: 
        name: "spotify"
        state: present

    - name: Install 1Password
      ignore_errors: True
      homebrew_cask: 
        name: "1password"
        state: upgraded
        greedy: True

    - name: Install Wireshark
      homebrew_cask: 
        name: "wireshark"
        state: present

    - name: Install Sublime Text
      homebrew_cask: 
        name: "sublime-text"
        state: present

    - name: Install Docker
      homebrew_cask: 
        name: "docker"
        state: present

    - name: Install google-cloud-sdk
      homebrew_cask: 
        name: "google-cloud-sdk"
        state: present

    - name: Install Insomnia
      homebrew_cask: 
        name: "insomnia"
        state: present

    - name: Install Google Chrome
      homebrew_cask: 
        name: "google-chrome"
        state: present

    - name: Install dotnet sdk
      homebrew_cask: 
        name: "dotnet-sdk"
        state: present
